[package]
name = "connect4_3d"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.22"
bevy = { version = "0.19", default-features = false, features = [
    "default_app",
    "std",
    "bevy_winit",
    "multi_threaded",
    "x11",
    "3d_bevy_render",
    "scene",
    "picking",
] }
tokio = { version = "1.32", features = ["rt", "sync", "time"] }
util = { package = "webrtc-util", version = "0.17.1", features = ["conn"] }
webrtc-ice = "0.17.1"
